spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkitout?useSSL=false&serverTimezone=UTC
    username: root
    password: Dmagmagma1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

gemini:
  api:
    key: AIzaSyCYDuSSJwpnkD2kjy7aF5Oz2Dgqvx7asWI
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent